"""new updates

Revision ID: 1e2fdf442cff
Revises: 
Create Date: 2024-07-13 18:45:12.238855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e2fdf442cff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('noteKey', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('noteKey')
    )
    op.create_table('circles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detail', sa.String(length=200), nullable=False),
    sa.Column('hashKey', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['hashKey'], ['elements.noteKey'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('circles')
    op.drop_table('elements')
    # ### end Alembic commands ###
